---
  - name: Deployment
    hosts: localhost
    gather_facts: true
    become: true
    collections:
      - ch_collections.base
    vars:
    roles:
      - role: /root/roles/nfs_mounts
        when: mounts is defined
      - name: ch_collections.base.cloudwatch_agent_config
        when: cw_log_files is defined or cw_collect_metrics is defined
    tasks: 
      - name: Retrieve instance metadata
        amazon.aws.ec2_metadata_facts:

      - name: Retrieve tags on instance
        amazon.aws.ec2_tag_info:
          region: "{{ ansible_ec2_placement_region }}"
          resource: "{{ ansible_ec2_instance_id }}"
        register: instance_tags

      - name: Set Hostname (1/2)
        ansible.builtin.lineinfile:
          line: "{{ item }} {{ instance_tags.tags.Name }}.{{ instance_tags.tags.Domain }} {{ instance_tags.tags.Name }}"
          regex: "^{{ item | regex_escape() }}.*$"
          path: "/etc/hosts"
        loop:
          - "{{ ansible_facts['all_ipv4_addresses'] }}"

      - name: Set Hostname (2/2)
        ansible.builtin.hostname:
          name: "{{ instance_tags.tags.Name }}.{{ instance_tags.tags.Domain }}"
          use: systemd
